development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_DATABASE_DEV'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: <%= ENV['DB_PORT'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_DATABASE_TEST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: <%= ENV['DB_PORT'] %>